nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
image:
  repository: heheh123/ecomm-config
  pullPolicy: IfNotPresent
  tag: dev
  digest: sha256:a25217a86edf9e351a1655e206dd76e21363942dc4aa3e9ad7da8ae30c34beff
service:
  type: ClusterIP
  port: 8080
configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: dev
livenessProbe: null
readinessProbe: null
image.digest: sha256:fde1fa32fa28b259f29a5f836c94716061e23b927631f1d6920bcc70622eca66
