nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
image:
  repository: heheh123/ecomm-config
  pullPolicy: IfNotPresent
  tag: dev
  digest: sha256:a25217a86edf9e351a1655e206dd76e21363942dc4aa3e9ad7da8ae30c34beff
service:
  type: ClusterIP
  port: 8080
configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: dev
livenessProbe: null
readinessProbe: null
image.digest: sha256:793b361b59292ddfbdc63527260adb119847a02f4ff1cab4d3d4a28831a3333c
