// high privilege config only!!!
@Library('core_lib') _

springBootAppCI(
    configFilePath: 'services/config-server/config.properties',
    configRepoUrl: 'https://github.com/nhan-n9/ecommerce-microservices-cicd.git',
    configRepoBranch: 'configs',
    deployConfigFile: 'ecomm-micro/dev/config-server.yaml'
)