name: Commit and Push to a repository

inputs:
  GIT_BRANCH:
  REPO_GIT_TOKEN:
  CONTEXT:

outputs:

runs:
  using: "composite"
  steps:
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        branch: ${{ inputs.GIT_BRANCH }}
        # need PAT at both checkout + push
        github_token: ${{ inputs.REPO_GIT_TOKEN }}
        directory: ${{ inputs.CONTEXT }}