name: Edit yaml file

inputs:
  EDIT_KEY:
    required: true
    type: string
  EDIT_VALUE:
    required: true
  TARGET_FILE_PATH:
    required: true
    description: full path to the target yaml file
    type: string

outputs:


runs:
  using: "composite"

  steps:
    - name: Update values in yaml file
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '."${{ inputs.EDIT_KEY }}" = "${{ inputs.EDIT_VALUE }}"' "${{ inputs.TARGET_FILE_PATH }}" 