name: Handle Maven build process

inputs:
  JAVA_VERSION:
    type: string
  SERVICE_NAME:
    type: string
  TEST_ENABLED:
    type: boolean


runs:
  using: "composite"

  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'maven'  # cache deps for faster builds


    # only run test if enabled
    - name: Run Maven test
      if: ${{ inputs.TEST_ENABLED }}
      working-directory: app/services/${{ inputs.SERVICE_NAME }}
      shell: bash
      run: mvn test


    - name: Build with Maven
      working-directory: app/services/${{ inputs.SERVICE_NAME }}
      shell: bash
      run: mvn clean package -DskipTests