
name: Main CI Workflow

on:   # when to trigger the workflow
  workflow_call:
    inputs:
      BUILD_TYPE:
        required: false
        type: string
        default: maven
      CICD_ENVIRONMENT:
        required: false
        type: string
        default: dev
      SERVICE_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      GIT_REPOSITORY:
        required: true
        type: string
      GIT_BRANCH:
        required: true
        type: string
        default: main
      PROJECT_NAME:
        required: true
        type: string
      BUILD_TOOL_VERSION:
        required: false
        type: string
        default: '21'   # default for mvn
      CODE_TEST_ENABLED:
        required: false
        type: boolean
        default: false
      TRIVY_SCAN_ENABLED:
        required: false
        type: boolean
        default: false
      SONAR_SCAN_ENABLED:
        type: boolean
        default: true
      SONAR_PROJECT_NAME:
        type: string
      SONAR_PROJECT_KEY:
        type: string

permissions:
  contents: read
  security-events: write
  actions: read

# env:
#   TRIVY_VERSION: 0.69.3

jobs:
  ci_jobs:
    runs-on: ubuntu-latest

    outputs:
      image-digest: ${{ steps.build-docker-image.outputs.digest }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.GIT_BRANCH }}
          path: app


      - name: Build source code
        uses: nhan-n9/ecommerce-microservices-cicd/.github/actions/handle-build-source@main
        with:
          SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
          BUILD_TOOL_VERSION: ${{ inputs.BUILD_TOOL_VERSION }}
          TEST_ENABLED: ${{ inputs.CODE_TEST_ENABLED }}
          BUILD_TYPE: ${{ inputs.BUILD_TYPE }}


      - if: ${{ inputs.SONAR_SCAN_ENABLED }}
        name: Setup Java for Sonar
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'


      - if: ${{ inputs.SONAR_SCAN_ENABLED }}
        name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v7
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # projectName: ${{ inputs.SONAR_PROJECT_NAME }}
          # projectKey: ${{ inputs.SONAR_PROJECT_KEY }}
          # url: https://sonarcloud.io
          # organization: nhan-n9


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        id: build-docker-image
        with:
          context: app/services/${{ inputs.SERVICE_NAME }}
          tags: ${{ inputs.IMAGE_NAME }}:${{ inputs.CICD_ENVIRONMENT }}
          push: true

      # Security scan for image
      - if: ${{ inputs.TRIVY_SCAN_ENABLED }}
        name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          cache: true
          version: latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: ${{ inputs.TRIVY_SCAN_ENABLED }}
        with:
          image-ref: ${{ inputs.IMAGE_NAME }}:${{ inputs.CICD_ENVIRONMENT }}
          format: sarif
          ignore-unfixed: true
          exit-code: '0'
          output: 'trivy-results.sarif'
          skip-setup-trivy: true
          scanners: vuln
          severity: HIGH,CRITICAL

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ inputs.TRIVY_SCAN_ENABLED }}
        with:
          sarif_file: 'trivy-results.sarif'
          category: trivy


  update_deploy_config:
    needs: ci_jobs
    uses: nhan-n9/ecommerce-microservices-cicd/.github/workflows/update-deploy.yaml@main
    secrets:
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
    with:
      EDIT_VALUE: ${{ needs.ci_jobs.outputs.image-digest }}
      TARGET_FILE_PATH: "${{ inputs.PROJECT_NAME }}/${{ inputs.CICD_ENVIRONMENT }}/${{ inputs.SERVICE_NAME }}.yaml"