
name: Test CICD Workflow

on:   # when to trigger the workflow
  workflow_call:
    inputs:
      BUILD_TYPE:
        required: false
        type: string
        default: maven
      CICD_ENVIRONMENT:
        required: false
        type: string
        default: dev
      SERVICE_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      GIT_REPOSITORY:
        required: true
        type: string
      GIT_BRANCH:
        required: true
        type: string
        default: main
      PROJECT_NAME:
        required: true
        type: string
      BUILD_TOOL_VERSION:
        required: false
        type: string
        default: '21'   # default for mvn
      CODE_TEST_ENABLED:
        required: false
        type: boolean
        default: false
      TRIVY_SCAN_ENABLED:
        required: false
        type: boolean
        default: false


jobs:
  checkout_resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow materials
        uses: actions/checkout@v4
        with:
          repository: nhan-n9/ecommerce-microservices-cicd
          token: ${{ secrets.TOKEN_GITHUB }}
          ref: main


      - name: Checkout source code
        uses: ./.github/actions/checkout
        with:
          GIT_REPOSITORY: ${{ github.repository }}
          GIT_BRANCH: ${{ inputs.GIT_BRANCH }}
          REPO_GIT_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          CONTEXT: "app"


  build_source:
    uses: ./.github/workflows/build-package.yaml
    with:
      SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
      BUILD_TOOL_VERSION: ${{ inputs.BUILD_TOOL_VERSION }}
      TEST_ENABLED: ${{ inputs.CODE_TEST_ENABLED }}
      BUILD_TYPE: ${{ inputs.BUILD_TYPE }}


  build_push_image:
    uses: ./.github/workflows/build-push-image.yaml
    with:
      IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
      IMAGE_TAG: ${{ inputs.CICD_ENVIRONMENT }}
      SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
      SECURITY_SCAN_ENABLED: ${{ inputs.TRIVY_SCAN_ENABLED }}
