name: Build source code

on:
  workflow_call:
    inputs:
      GIT_BRANCH:
        type: string
      SERVICE_NAME:
        type: string
      TARGET_FILE_PATH:
        type: string
      EDIT_VALUE:
        type: string


jobs:
  update_deploy_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config source
        uses: ./.github/actions/checkout
        with:
          GIT_REPOSITORY: nhan-n9/ecommerce-microservices-cicd
          GIT_BRANCH: configs
          REPO_GIT_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          CONTEXT: "service-configs"


      - name: Update new image digest
        uses: ./.github/actions/edit-yaml
        with:
          TARGET_FILE_PATH: "service-configs/${{ inputs.PROJECT_NAME }}/${{ inputs.CICD_ENVIRONMENT }}/${{ inputs.SERVICE_NAME }}.yaml"
          EDIT_KEY: "image.digest"
          EDIT_VALUE: "${{ steps.process-image.outputs.image-digest }}"

      
      # push to the config repo for GitOps
      - name: Commit & Push changes
        uses: ./.github/actions/commit-push
        with:
          GIT_BRANCH: ${{ inputs.GIT_BRANCH }}
          REPO_GIT_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          CONTEXT: "service-configs"