name: Build source code

on:
  workflow_call:
    inputs:
      TARGET_FILE_PATH:
        type: string
      EDIT_VALUE:
        type: string
      CONFIG_BRANCH:
        type: string
        default: configs
      CONFIG_REPO:
        type: string
        default: nhan-n9/ecommerce-microservices-cicd
    secrets:
      TOKEN_GITHUB:
        required: true

jobs:
  update_deploy_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.CONFIG_REPO }}
          ref: ${{ inputs.CONFIG_BRANCH }}
          token: ${{ secrets.TOKEN_GITHUB }}


      - name: Update new image digest
        uses: nhan-n9/ecommerce-microservices-cicd/.github/actions/edit-yaml@main
        with:
          TARGET_FILE_PATH: "${{ inputs.TARGET_FILE_PATH }}"
          EDIT_KEY: "image.digest"
          EDIT_VALUE: "${{ inputs.EDIT_VALUE }}"

      
      # push to the config repo for GitOps
      - uses: actions-js/push@master
        with:
          # need PAT at both checkout + push
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: ${{ inputs.CONFIG_BRANCH }}
          repository: ${{ inputs.CONFIG_REPO }}